### ISSUE TITLE
Can sin install just runit-base?

### ISSUE THREAD

**Issue by Tank-Missile** [cloux/sin#1]
I looked at the runit-init module and it does a lot more than I need. I suppose I could just do a git clone of runit-base once in a while, but sin does an update check, handles directory structure, etc. Basically, I just need runit-base, since I assume using runit-init, as well as everything else Devuan provides will suffice. If you think I'm wrong in this assumption, enlighten me on the subject. If I'm going to use a Debian based distro without systemd or sysvinit with runit as PID 1 and as an init system, is runit-base truly enough?

**Comment by cloux** [comment]
The [runit-init module](https://github.com/cloux/sin/blob/master/modules/runit-init/install) in SIN was made to rebuild a sysvinit-based OS into a runit-init based system, by a single command. To modify that runit-init SIN module, you can for example:

```
mkdir -p /usr/local/share/sin/runit-base
cp /usr/share/sin/runit-init/install /usr/local/share/sin/runit-base/
```

and then edit the file _/usr/local/share/sin/runit-base/install_ as you wish. Feel free to delete anything you don't need, the functional sections are marked in comments.  You can run your new modified script anytime by executing `sin runit-base`.

WARNING: If you delete everything and just keep the runit-base part, there will be some problems. Don't expect the stability of such system to be anywhere near my AWS EC2 instance. Dpkg and subsequently apt-get will not work properly, services will not start or restart, acpi power management will fail, Runit as installed from Debian/Devuan repository will be pulling conflicting dependencies like "getty-run", etc. The runit-init version in the repository still has some security issues. I fixed them and contributed the fixes, but the fixed version is currently only available in the 'unstable' repository. I recommend pulling and compilling my sources [here](https://github.com/cloux/runit). Also there is no "socklog" in the repository and must be compiled from source. Socklog (e.g. syslog replacement) is a dependency in some of my runscripts (incron). At the end, you might find that the runit-base alone is just not enough, and there is not much overhead in my _runit-init_ installer.
